baseURL = "https://www.jakoubek.net/"
languageCode = "de-de"
title = "Oliver Jakoubek Software & Beratung"
theme = "jakoubek"
enableGitInfo = true
pygmentsUseClasses=true

[params]
matomoSiteId = 1
panelbearSiteId = "IS0PpffxsSv"
description = "Oliver Jakoubek konzipiert und entwickelt datenbankbasierte Individualsoftware und Reporting-Frontends für moderne Unternehmen."
