name: website deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1 - Checks-out your repository
      - name: Checkout
        uses: actions/checkout@main

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public

      # Step 4 - Builds the site using the latest version of Hugo
      - name: Build
        run: hugo --minify

      # Step 5 - Deploy via scp to Opalstack
      - name: deploy website to jakoubek.net
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "public/*"
          target: "/home/oli/apps/jakoubek_www"
          strip_components: 1
